title    : "Timothée Schmoderer"
url      : https://tschmoderer.github.io
locale   : "en"
encoding : "utf-8"

# Build settings
exclude:
  - LICENSE
  - Gemfile
  - Gemfile.lock

include:
  - _pages
  - _teaching

sass:
  sass_dir: _sass
  style: compressed 

# Conversion
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
markdown: kramdown